#!/usr/bin/env python3

import asyncio
import datetime
import os
import sys
import time
import traceback

import fmt
import config
import handlers
import secrets

from irctokens import build, Line
from ircrobots import Bot as BaseBot
from ircrobots import Server as BaseServer
from ircrobots import ConnectionParams, SASLUserPass, SASLSCRAM

from misc import whoami

# cache output, module name on a per-channel basis
# this is for self.msg and self.more
output_buf = {}
last_modname = {}

class Server(BaseServer):
    def log(self, mod, txt):
        now = datetime.datetime.now()
        fmt = datetime.datetime.strftime(now, '%Y-%M-%dT%H:%m:%SZ')
        print(f'{fmt}: [{mod}]: {txt}')

    async def load_mods(self):
        for i in [s for s in os.listdir('mod') if '.py' in s]:
            i = i[:-3]
            self.log('modules', f'loading {i}')
            m = __import__('mod.' + i)
            m = eval('m.' + i)
            asyncio.create_task(m.init(self))
            self.modules[i] = m

    # -----

    async def line_read(self, line: Line):
        if "on_" + line.command.lower() in dir(self):
            asyncio.create_task(
                self.__getattribute__("on_" + line.command.lower())(line)
            )
        #for listener in shared.listeners:
        #    if listener[0] == line.command:
        #        asyncio.create_task(listener[1](self, line))

    def line_preread(self, line: Line):
        self.log("raw", f"RECV: {self.name} <- {line.format()}")

    def line_presend(self, line: Line):
        self.log("raw", f"SEND: {self.name} -> {line.format()}")

    async def on_invite(self, line):
        self.log('irc', 'received invite by {} to {}'.format(by, chan))

        if config.join_on_invite:
            if chan not in config.bannedchans:
                await self.join(chan)

    async def on_001(self, line):
        self.log('irc', 'connected!')

        self.background_tasks = set()
        self.fndata = {}
        self.modules = {}
        self.help = {}
        self.userinfo = {}
        self.aliases = {}

        # handle commands, raw PRIVMSGs,
        # and messages that match a regex,
        # respectively.
        self.handle_cmd = {}
        self.handle_raw = {}
        self.handle_reg = {}

        # HACK: avoid executing commands from
        # channel history playback
        self.ignore_cmd = 0

        self.log('modules', 'loading modules...')
        await self.load_mods()
        self.log('modules', 'done!')

        self.log('irc', 'joining channels')
        for i in config.initial_chans:
            await self.join(i)
        self.log('irc', 'done!')

        if config.set_botmode:
            self.log('irc', 'attempting to set mode +B')
            await self.set_mode(self.nickname, '+B')

    async def on_join(self, line):
        source = line.source.split("!")[0]
        chan, msg = line.params[0], line.params[1]

        if source == self.nickname:
            self.ignore_cmd = time.time() + 1

    async def on_privmsg(self, line):
        # Skip batched messages, like channel history and bouncer playback
        if line.tags and "batch" in line.tags and line.tags["batch"] == "1":
            return

        source = line.source.split("!")[0]
        chan, msg = line.params[0], line.params[1]

        # ignore channel playback on channels that have
        # mode +H (only on ircv3 servers)
        #if not time.time() > self.ignore_cmd:
        #    self.log("irc", "ignoring")
        #    return

        for i in self.handle_raw:
            await self.handle_raw[i](self, chan, source, msg)

        if source == self.nickname:
            return

        if msg == '!botlist' or msg == '!rollcall':
            if config.respond_to_rollcall:
                await whoami(self, chan, source, msg)
            return

        if not chan in self.asleep:
            self.asleep[chan] = 0

        for i in self.handle_reg:
            # (<regex>, <function>)
            if not self.handle_reg[i][0].match(msg):
                continue
            await self.handle_reg[i][1](self, chan, source, msg)

        if not msg[:len(self.prefix)] == self.prefix:
            return

        msg = msg[len(self.prefix):]
        cmd = msg.split(' ')[0]
        msg = msg[len(cmd) + 1:]

        # check if the command might be an alias
        matches = {k for k, v in self.aliases.items() if cmd in v}
        if len(matches) > 0 and cmd not in self.handle_cmd:
            cmd = list(matches)[0]

        if cmd in self.handle_cmd:
            self.log('irc', 'recieved command "{} {}" from "{}" in "{}"'
                .format(cmd, msg, source, chan))
            func = self.handle_cmd[cmd]

            if self.asleep[chan] < time.time() or cmd == 'admin':
                try:
                    await handlers.execute(self, func, chan, source, msg)
                except Exception as e:
                    traceback.print_tb(e.__traceback__)
                    if func in self.fndata:
                        module = self.fndata[func]['module']
                    else:
                        module = 'oops'
                    await self.msg(module, chan, ['segmentation fault', repr(e)])
                    return

    async def msg(self, mod, chan, msg: list):
        # TODO: throttling (if the messages are too big)
        if chan in output_buf:
            del output_buf[chan]
        output_buf[chan] = msg[:]  # copy list
        last_modname[chan] = mod

        msg_fmted = "{}"
        if len(last_modname[chan]) > 1:
            msg_fmted = fmt.modname(last_modname[chan]) + " " + msg_fmted

        if len(output_buf[chan]) > 1:
            msg_fmted = msg_fmted + " (more)"

        await self.message(chan, msg_fmted.format(output_buf[chan].pop(0)))

    async def more(self, chan):
        if len(output_buf[chan]) == 0:
            await self.message(
                chan, "{} no more text to show".format(fmt.modname("more"))
            )
            return

        msg_fmted = "{}"
        if len(last_modname[chan]) > 1:
            msg_fmted = fmt.modname(last_modname[chan]) + " " + msg_fmted
        if len(output_buf[chan]) > 1:
            msg_fmted = msg_fmted + " (more)"

        await self.message(chan, msg_fmted.format(output_buf[chan].pop(0)))

    async def is_admin(self, nickname):
        l = nickname.lower()
        return l in self.users and self.users[l].account in config.admins

    #async def on_ctcp(self, by, chan, what, contents):
    #    # treat actions as normal messages
    #    if what == 'ACTION':
    #        await self.on_channel_message(chan, by, f"{what} {contents}")

    #async def on_user_mode_change(self, modes):
    #    self.log('irc', 'mode changed: {}'.format(modes))

    # Pydle compat
    # ----

    async def action(self, chan: str, message: str):
        await self.send(build("PRIVMSG", [chan, f"\x01ACTION {message}\x01"]))

    async def part(self, chan: str):
        #await self.send_part(chan, None)
        self.send(build("PART", [chan]))

    async def join(self, chan: str):
        #async def j(s, c):
        #    await s.send_join(c, None)
        #t = asyncio.create_task(j(self, chan))
        #self.background_tasks.add(t)
        #t.add_done_callback(self.background_tasks.discard)
        self.send(build("JOIN", [chan]))

    async def joins(self, chans):
        #await asyncio.create_task(self.send_joins(chans, []))
        self.send(build("JOIN", chans))

    async def set_mode(self, nick, modes):
        await self.send(build("MODE", [nick, modes]))

    async def message(self, channel, s):
        await self.send(build("PRIVMSG", [channel, s]))

    async def quit(self, msg):
        await self.send(build("QUIT", [msg]))

class Bot(BaseBot):
    def create_server(self, name: str):
        s = Server(self, name)
        s.prefix = config.prefix
        s.asleep = {}
        return s

async def main():
    bot = Bot()

    params = ConnectionParams(
        config.nickname,
        config.server,
        port = 6667,
        tls = None,
        sasl = SASLUserPass(config.username, secrets.sasl_password),
    )

    await bot.add_server("tilde.chat", params)
    await bot.run()

if __name__ == "__main__":
    asyncio.run(main())
